[package]
name = "checked-copy"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imprint = { git = "https://github.com/archer884/imprint" }
structopt = "0.3.22"
walkdir = "2.3.2"
